version: '3.7'
services:
  web-mkt:
    image: node
    volumes:
      - ./:/app
    working_dir: /app
    command: npm start
    environment:
      SERVER_PORT: 3000
      MONGO_URL: "mongodb://mkt-usuario:mkt-senha@mongo-mkt:27017/mkt?authSource=admin"
      RABBITMQ_HOST: 'rabbitmq'
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
      - mongo-mkt

  mongo-mkt:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mkt-usuario
      MONGO_INITDB_ROOT_PASSWORD: mkt-senha
      MONGO_INITDB_DATABASE: mkt

  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
